---
title: "rating_data"
author: "Adam A. Bramlett"
date: "2024-01-06"
output: html_document
---

```{r setup, include=FALSE}
getwd()
path<-list.files("/Users/adambramlett/scripts/music_project_23/data/sing_ratings",full.names =TRUE)
```
```{r}

path[1]
data1<-read.csv(paste(path[1]))
View(data1)

library(dplyr)

data1<-data1%>%
  mutate(Rhythm=as.numeric(Rhythm),
        Pitch=as.numeric(Pitch),
         Pronunciation.diction=as.numeric(Pronunciation.diction),
         Rerformance=as.numeric(Performance))%>%
  filter(!is.na(Pitch))%>%
  na.omit()

j_data<-data1%>%
  filter(Scorer=="J")
z_data<-data1%>%
  filter(Scorer=="z")

cronbach_alpha <- cronbach.alpha(data1%>%select(Rhythm,Pitch,Pronunciation.diction,Rerformance))
singing_cronbach_alpha<-cronbach_alpha
print(singing_cronbach_alpha)


path[2]
data2<-read.csv(paste(path[2]))
View(data2)
library(dplyr)

data2<-data2%>%
  mutate(Rhythm=as.numeric(Rhythm),
        Pitch=as.numeric(Pitch),
         Pronunciation.diction=as.numeric(Pronunciation.diction),
         Rerformance=as.numeric(Performance))%>%
  filter(!is.na(Pitch))%>%
  na.omit()

colnames(data1)

cronbach_alpha <- cronbach.alpha(data1%>%select(Rhythm,Pitch,Pronunciation.diction,Rerformance))
singing_cronbach_alpha<-cronbach_alpha
print(singing_cronbach_alpha)
```


